<a href="https://colab.research.google.com/github/sambit2407/NLP/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.Train own embedding using Word2Vec library

In [ ]:
sentences=['Hi let us learn NLP together','What is word embedding','NLP is part of data science','I love playing cricket','i do not like to play football']

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.tokenize import word_tokenize

In [ ]:
sent_token=[]

for sent in sentences:
  sent_word= word_tokenize(sent)
  sent_token.append(sent_word)
    




In [ ]:
sent_token

[['Hi', 'let', 'us', 'learn', 'NLP', 'together'],
 ['What', 'is', 'word', 'embedding'],
 ['NLP', 'is', 'part', 'of', 'data', 'science'],
 ['I', 'love', 'playing', 'cricket'],
 ['i', 'do', 'not', 'like', 'to', 'play', 'football']]

In [ ]:
#training word2vec model
from gensim.models import Word2Vec


In [ ]:
model2=Word2Vec(sent_token,size=100, window=3, min_count=1, workers=4)

In [ ]:
model2.wv.vocab

{'Hi': <gensim.models.keyedvectors.Vocab at 0x7fadf4798b90>,
 'I': <gensim.models.keyedvectors.Vocab at 0x7fadf4798cd0>,
 'NLP': <gensim.models.keyedvectors.Vocab at 0x7fadf47985d0>,
 'What': <gensim.models.keyedvectors.Vocab at 0x7fadf4798b10>,
 'cricket': <gensim.models.keyedvectors.Vocab at 0x7fadf477d250>,
 'data': <gensim.models.keyedvectors.Vocab at 0x7fadf4798d90>,
 'do': <gensim.models.keyedvectors.Vocab at 0x7fadf477db90>,
 'embedding': <gensim.models.keyedvectors.Vocab at 0x7fadf4798fd0>,
 'football': <gensim.models.keyedvectors.Vocab at 0x7fadf477d850>,
 'i': <gensim.models.keyedvectors.Vocab at 0x7fadf477ddd0>,
 'is': <gensim.models.keyedvectors.Vocab at 0x7fadf4798690>,
 'learn': <gensim.models.keyedvectors.Vocab at 0x7fadf4798890>,
 'let': <gensim.models.keyedvectors.Vocab at 0x7fadf4798590>,
 'like': <gensim.models.keyedvectors.Vocab at 0x7fadf477d510>,
 'love': <gensim.models.keyedvectors.Vocab at 0x7fadf4798850>,
 'not': <gensim.models.keyedvectors.Vocab at 0x7fadf477d

In [ ]:
type(model2.wv.vocab)

dict

In [ ]:
list(model2.wv.vocab)

['Hi',
 'let',
 'us',
 'learn',
 'NLP',
 'together',
 'What',
 'is',
 'word',
 'embedding',
 'part',
 'of',
 'data',
 'science',
 'I',
 'love',
 'playing',
 'cricket',
 'i',
 'do',
 'not',
 'like',
 'to',
 'play',
 'football']

In [ ]:
model2.wv['data']

array([-4.32538148e-03, -2.14903778e-03,  4.51367319e-04, -2.59711151e-03,
        6.30027091e-04,  7.94260937e-04,  2.83615175e-03, -2.15511653e-03,
       -4.36740927e-03, -3.54983960e-03, -1.53123878e-03,  3.87490890e-03,
       -1.44823658e-04,  7.14701950e-04,  2.56880210e-03, -2.67815846e-03,
       -2.98538595e-03, -9.30016453e-04, -2.05675839e-03, -2.16101273e-03,
       -2.49570130e-05,  1.15435039e-04, -1.79214025e-04, -5.69734199e-04,
       -4.96254722e-03,  4.97373426e-03,  2.47723982e-03, -4.81544295e-03,
       -1.99572160e-03, -3.34981526e-03, -2.24417471e-03,  4.08531306e-03,
       -4.38039145e-03,  3.70976562e-03,  7.23179372e-04, -1.63793610e-03,
        2.82532512e-03,  1.02656395e-05, -7.45358295e-04,  2.23295647e-03,
       -3.50306183e-03,  1.78935169e-03,  4.05579573e-03, -3.52750206e-03,
       -6.47986832e-04, -1.52527925e-03,  4.64066071e-03, -4.41653281e-03,
        1.01653545e-03,  3.72587517e-03, -2.18889769e-03, -3.54560651e-03,
        5.54450962e-04, -

In [ ]:
model2.wv.most_similar('cricket')

[('is', 0.21683955192565918),
 ('data', 0.14938336610794067),
 ('football', 0.1486794501543045),
 ('together', 0.12523873150348663),
 ('What', 0.11113680154085159),
 ('do', 0.10081343352794647),
 ('part', 0.08613753318786621),
 ('not', 0.08156951516866684),
 ('i', 0.06304539740085602),
 ('playing', 0.03779919445514679)]

In [ ]:
#disadvantages
model2.wv.most_similar('hockey')

KeyError: ignored

In [ ]:
pd.read_excel('spamdata.xlsx')

ham  \
0      ham   
1     spam   
2      ham   
3      ham   
4     spam   
...    ...   
5566  spam   
5567   ham   
5568   ham   
5569   ham   
5570   ham   

     Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
0                         Ok lar... Joking wif u oni...                                                               
1     Free entry in 2 a wkly comp to win FA Cup fina...                                                               
2     U dun say so early hor... U c already then say...                                                               
3     Nah I don't think he goes to usf, he lives aro...                                                               
4     FreeMsg Hey there darling it's been 3 week's n...                                                               
...                                                 ...                                                               
5566  This is the 2nd time we have tried 2 contact u...                                                               
5567               Will ü b going to esplanade fr home?                                                               
5568  Pity, * was in mood for that. So...any other s...                                                               
5569  The guy did some bitching but I acted like i'd...                                                               
5570                         Rofl. Its true to its name                                                               

[5571 rows x 2 columns]

# 3. Train own Embedding Keras Embedding Method.

In [ ]:
sentences=["FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv","WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.","SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info","U dun say so early hor... U c already then say..","I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.","I HAVE A DATE ON SUNDAY WITH WILL!!"]

In [ ]:
import numpy as np
sent_labels=np.array([1,1,1,0,0,0])

In [ ]:
type(sentences)

list

In [ ]:
data=pd.DataFrame(data=zip(sentences,sent_labels),columns=['msg','labels'])

In [ ]:
data

msg  labels
0  FreeMsg Hey there darling it's been 3 week's n...       1
1  WINNER!! As a valued network customer you have...       1
2  SIX chances to win CASH! From 100 to 20,000 po...       1
3   U dun say so early hor... U c already then say..       0
4  I'm gonna be home soon and i don't want to tal...       0
5                I HAVE A DATE ON SUNDAY WITH WILL!!       0

In [ ]:
import re
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
ps=PorterStemmer()
def clean(data):
  corpus=[]
  for i in range(0,len(data['msg'])):
    print(i)
    msg=re.sub('[^a-zA-Z]',' ',data['msg'][i])
    msg=msg.split()
    msg=[ps.stem(word) for word in msg if not word in stopwords.words('english')]
    msg = ' '.join(msg)
    corpus.append(msg)
    
  
    
  return corpus



In [ ]:
corpus=clean(data)

0
1
2
3
4
5


In [ ]:
corpus

['freemsg hey darl week word back I like fun still Tb ok xxx std chg send rcv',
 'winner As valu network custom select receivea prize reward To claim call claim code KL valid hour',
 'six chanc win cash from pound txt csh send cost p day day tsandc appli repli HL info',
 'U dun say earli hor U c alreadi say',
 'I gonna home soon want talk stuff anymor tonight k I cri enough today',
 'I have A date ON sunday with will']

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [ ]:
#encoding
voc_size=50
onehot_repr= [one_hot(sent,voc_size)for sent in corpus] 
onehot_repr

[[46, 21, 1, 32, 39, 25, 24, 10, 30, 25, 47, 35, 44, 1, 6, 49, 10],
 [4, 4, 4, 2, 25, 3, 30, 42, 16, 33, 1, 10, 1, 14, 11, 4, 6],
 [44, 46, 1, 6, 20, 6, 26, 16, 49, 4, 14, 47, 47, 26, 48, 34, 6, 18],
 [48, 43, 24, 11, 47, 48, 49, 38, 24],
 [24, 13, 14, 27, 49, 27, 18, 8, 43, 33, 24, 39, 4, 6],
 [24, 8, 18, 44, 33, 38, 9, 10]]

In [ ]:
sent_length=18
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[ 0 46 21  1 32 39 25 24 10 30 25 47 35 44  1  6 49 10]
 [ 0  4  4  4  2 25  3 30 42 16 33  1 10  1 14 11  4  6]
 [44 46  1  6 20  6 26 16 49  4 14 47 47 26 48 34  6 18]
 [ 0  0  0  0  0  0  0  0  0 48 43 24 11 47 48 49 38 24]
 [ 0  0  0  0 24 13 14 27 49 27 18  8 43 33 24 39  4  6]
 [ 0  0  0  0  0  0  0  0  0  0 24  8 18 44 33 38  9 10]]


In [ ]:
#defining model
feature_size=100
model3=Sequential()
model3.add(Embedding(voc_size,feature_size,input_length=sent_length,name='embedding'))
model3.add(Flatten())
model3.add(Dense(1,activation='sigmoid'))


In [ ]:
print(model3.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 18, 100)           5000      
                                                                 
 flatten_3 (Flatten)         (None, 1800)              0         
                                                                 
 dense_3 (Dense)             (None, 1)                 1801      
                                                                 
Total params: 6,801
Trainable params: 6,801
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model3.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
## Finally Training
model3.fit(embedded_docs,sent_labels,epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 493ms/step - loss: 0.6815 - accuracy: 0.6667
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6602 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6393 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6188 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.5987 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 0.5789 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5594 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 5ms/step - loss: 0.5402 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5212 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5024 - accuracy: 1.0000
Epoch 11/50
1/1 [====================

In [ ]:
weights=model3.get_layer('embedding').get_weights()[0]
len(weights)

50

In [ ]:
model3.get_layer('embedding').get_weights()[0][0]

array([-0.05088669,  0.07897494, -0.00584384,  0.06396876, -0.05561905,
       -0.05579843, -0.0517165 ,  0.06799003,  0.06712596,  0.03831484,
       -0.04921581,  0.08876541,  0.04588452, -0.05338224,  0.07648774,
       -0.07441556, -0.02985643,  0.07981911, -0.07116101,  0.06564176,
        0.0870227 ,  0.09634245,  0.04462949,  0.09157773,  0.08262053,
        0.04492938, -0.05561057,  0.08816829,  0.00651117,  0.09665502,
        0.04821563,  0.09619991,  0.03453307,  0.08510207,  0.01613446,
        0.04265289,  0.02492401,  0.0060581 , -0.06689785, -0.06797598,
       -0.05600508,  0.01739041, -0.05100049, -0.00560202,  0.05712852,
       -0.09245466, -0.04129357,  0.04717566,  0.08897859,  0.07072297,
       -0.03317908,  0.0635272 , -0.06285261, -0.07426315,  0.09212562,
       -0.00700971, -0.07775054,  0.05974125,  0.08144593, -0.03236569,
       -0.07704405,  0.02912599, -0.07945553,  0.0694673 ,  0.04725306,
       -0.05269183, -0.0095155 , -0.07017071,  0.02209825, -0.04

In [ ]:
weights[4]#winner

array([-0.00141833, -0.05452403, -0.004335  , -0.06421278, -0.07231916,
        0.02220725,  0.09259204, -0.00541454, -0.05562538, -0.00800391,
        0.01952702, -0.05310063,  0.00974942,  0.04018967, -0.03069899,
       -0.05986988, -0.00062018, -0.04519001,  0.02953283, -0.08563048,
       -0.08803567, -0.00973329, -0.06534764, -0.06900775, -0.08597003,
       -0.08855874,  0.08638977, -0.07231213,  0.094473  , -0.00727638,
       -0.04959695, -0.04651417, -0.0927881 , -0.02965708,  0.0856545 ,
       -0.01792906, -0.07822265, -0.04767412,  0.00531864, -0.06930999,
        0.04293835, -0.0798641 ,  0.02996519,  0.07854383, -0.09193312,
        0.0506038 ,  0.02708785, -0.08281946, -0.06968389, -0.0075558 ,
        0.02349916, -0.04248148, -0.00758745,  0.05949486, -0.08328461,
        0.00430191,  0.05799831,  0.05857727, -0.04338959,  0.04618945,
        0.08344917, -0.0267438 ,  0.06164882, -0.04684909, -0.04625686,
        0.00244602, -0.01101503,  0.03364303, -0.09706351,  0.05

In [ ]:
weights[1]#win

array([-0.00698507, -0.02274259, -0.09211595,  0.07729302,  0.06247756,
       -0.04246807,  0.07423294, -0.06655995, -0.02915058,  0.04032254,
        0.09558517, -0.05416711,  0.00107342,  0.0174354 ,  0.00703362,
        0.0565705 ,  0.04829713,  0.00533972,  0.00663676, -0.02112168,
       -0.01623414, -0.00828128, -0.07192114, -0.0378823 ,  0.06146321,
        0.05320144,  0.06826852, -0.01392491,  0.08315222, -0.02215963,
        0.05704975,  0.00167748, -0.05890344,  0.07731482, -0.00353206,
       -0.06105121, -0.04393622,  0.08478707, -0.078983  ,  0.02848827,
       -0.01725299, -0.02914831,  0.07040447, -0.08854671,  0.03454999,
        0.07159922,  0.09182974, -0.06467129,  0.02190165, -0.02042896,
        0.07309007, -0.00191633, -0.00546666,  0.06267189, -0.04303234,
       -0.00103132,  0.08669166,  0.03932037, -0.04176356,  0.02212811,
        0.0820915 , -0.01938197, -0.02746456, -0.05739615,  0.01623478,
        0.00195361, -0.08776957,  0.03306731,  0.00187353, -0.08

# Prediction for New Message

In [ ]:
sents=["URGENT! You have won a 1 week FREE membership in our £100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18","WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.","	Nah I don't think he goes to usf, he lives around here though"]

In [ ]:
pred_data=pd.DataFrame(data=sents,columns=['msg'])
pred_data

msg
0  URGENT! You have won a 1 week FREE membership ...
1  WINNER!! As a valued network customer you have...
2  \tNah I don't think he goes to usf, he lives a...

In [ ]:
pred_corpus=clean(pred_data)

0
1
2


In [ ]:
pred_corpus

['urgent you week free membership prize jackpot txt word claim No T C www dbuk net lccltd pobox ldnw A RW',
 'winner As valu network custom select receivea prize reward To claim call claim code KL valid hour',
 'nah I think goe usf live around though']

In [ ]:
#encoding

onehot_repr= [one_hot(words,voc_size)for words in pred_corpus] 
onehot_repr

[[14,
  17,
  32,
  6,
  4,
  42,
  36,
  26,
  39,
  1,
  8,
  16,
  49,
  20,
  25,
  44,
  10,
  12,
  10,
  18,
  20],
 [4, 4, 4, 2, 25, 3, 30, 42, 16, 33, 1, 10, 1, 14, 11, 4, 6],
 [12, 24, 49, 8, 26, 20, 14, 14]]

In [ ]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[ 6  4 42 36 26 39  1  8 16 49 20 25 44 10 12 10 18 20]
 [ 0  4  4  4  2 25  3 30 42 16 33  1 10  1 14 11  4  6]
 [ 0  0  0  0  0  0  0  0  0  0 12 24 49  8 26 20 14 14]]


In [ ]:
prediction = (model3.predict(embedded_docs) > 0.5).astype("int32")
prediction

array([[1],
       [1],
       [0]], dtype=int32)